### ISSUE TITLE
Builds after 4.3.2 do not connect properly to trackers

### ISSUE THREAD

**Issue by inertia666** [chrisjohnson00/docker-qBittorrentvpn#36]
I have tried all builds after 4.3.2 up to and including 4.3.5 but none of the builds are connecting properly to the trackers. When I go to the respective sites to check what I am seeding they do not appear on the seeding list. Examining the tracker page in the client shows that they are not connecting.

Only 4.3.2 is properly working (for me and my VPN at least). I have not tried to test without a VPN in the container.

**Comment by chrisjohnson00** [comment]
Sup dude, I'm running the `latest` tag on my Kubernetes cluster at home, and it's been working fine for me.
I'll take a closer look after work sometime, but AFAIK it's working fine.
FWIW, my automation is just installing whatever the latest version is available from `apt` repos, so if this is a bug, it's likely not with my automation, especially if you get the app to run at all.

**Comment by inertia666** [comment]
Could be only a problem with private trackers or in combination with my VPN provider. I have tested every new version since 4.3.2 and they don't work for me.

**Comment by chrisjohnson00** [comment]
![image](https://user-images.githubusercontent.com/1231933/121443489-700f2f80-c942-11eb-9e67-dda2e553d91c.png)

Yes, I think you could be right.  Looks like in my client I have no issues with up/down.  The above is for the last 48 hours or so.

**Comment by inertia666** [comment]
I will do some more tests and try and nail down where the issue lies.

**Comment by inertia666** [comment]
All private trackers cannot connect but public trackers are ok. I have tried disabling DHT, PEX and LSD  but it doesn't help. 

https://torguard.net/checkmytorrentipaddress.php connects and shows the VPN ip address.

**Comment by inertia666** [comment]
Ok made some tests:

1) Run QBT 4.3.5 without VPN in Docker container - cannot connect to the same trackers I am having a problem with
2) Run QBT 4.3.5 On Windows 10 with VPN Client installed - Works as normal, all trackers connected

So this is issue does seem restricted to the container and version of QBT installed. I will now return to 4.3.2 where everything works normally.

**Comment by inertia666** [comment]
Finally found out how to fix it

In advanced settings check "Support internationalized domain name (IDN) (requires libtorrent >= 1.2.12): (?)"

and possibly uncheck "Validate HTTPS tracker certificat"
