### ISSUE TITLE
Connection Reset / qbittorrent-nox: error while loading shared libraries: libQt5Core.so.5: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by lgaudreau** [chrisjohnson00/docker-qBittorrentvpn#46]
I've just installed the 'latest' (as of Sept 18) for amd64 on Synology DS416Play; Thanks for forking this!  

When trying to access the web interface was receiving a 'connection reset'. When trying to run 'qbittorrent-nox' from the container, received the error:
qbittorrent-nox: error while loading shared libraries: libQt5Core.so.5: cannot open shared object file: No such file or directory

This was resolved by following the instructions from https://github.com/linuxserver/docker-qbittorrent/issues/103#issuecomment-778796082

    Attach to docker container
    apt update
    apt install binutils
    strip --remove-section=.note.ABI-tag /usr/lib/x86_64-linux-gnu/libQt5Core.so.5

After restarting the container the issue is resolved.

**Comment by chrisjohnson00** [comment]
@lgaudreau mind helping me test?
`chrisjohnson00/qbittorrent-openvpn:issue-46`
It seems to work on my machine, but that's latest kernel.
